# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Tue Jun  4 22:21:51 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.year_edit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_edit.sizePolicy().hasHeightForWidth())
        self.year_edit.setSizePolicy(sizePolicy)
        self.year_edit.setObjectName("year_edit")
        self.horizontalLayout.addWidget(self.year_edit)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.month_edit = QtWidgets.QLineEdit(Form)
        self.month_edit.setObjectName("month_edit")
        self.horizontalLayout.addWidget(self.month_edit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.day_edit = QtWidgets.QLineEdit(Form)
        self.day_edit.setObjectName("day_edit")
        self.horizontalLayout.addWidget(self.day_edit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(533, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hour_edit = QtWidgets.QLineEdit(Form)
        self.hour_edit.setObjectName("hour_edit")
        self.horizontalLayout_2.addWidget(self.hour_edit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.minute_edit = QtWidgets.QLineEdit(Form)
        self.minute_edit.setObjectName("minute_edit")
        self.horizontalLayout_2.addWidget(self.minute_edit)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.second_edit = QtWidgets.QLineEdit(Form)
        self.second_edit.setObjectName("second_edit")
        self.horizontalLayout_2.addWidget(self.second_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(533, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lbl_info = QtWidgets.QLabel(Form)
        self.lbl_info.setObjectName("lbl_info")
        self.verticalLayout.addWidget(self.lbl_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_button = QtWidgets.QPushButton(Form)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout_3.addWidget(self.edit_button)
        self.fix_button = QtWidgets.QPushButton(Form)
        self.fix_button.setObjectName("fix_button")
        self.horizontalLayout_3.addWidget(self.fix_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "年", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "月", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "日", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", ":", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", ":", None, -1))
        self.lbl_info.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
        self.edit_button.setText(QtWidgets.QApplication.translate("Form", "调整", None, -1))
        self.fix_button.setText(QtWidgets.QApplication.translate("Form", "校准", None, -1))

