# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Wed Apr 17 20:53:17 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 657)
        MainWindow.setWindowOpacity(0.95)
        MainWindow.setStyleSheet("background: rgb(230, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.linedit_expr = QtWidgets.QLineEdit(self.centralwidget)
        self.linedit_expr.setStyleSheet("background: rgba(255, 255, 255, 0);color: rgb(136, 136, 136);border:none;\n"
"")
        self.linedit_expr.setText("")
        self.linedit_expr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linedit_expr.setReadOnly(True)
        self.linedit_expr.setObjectName("linedit_expr")
        self.verticalLayout.addWidget(self.linedit_expr)
        self.linedit_res = QtWidgets.QLineEdit(self.centralwidget)
        self.linedit_res.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.linedit_res.setFont(font)
        self.linedit_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.linedit_res.setAutoFillBackground(False)
        self.linedit_res.setStyleSheet("background: rgba(255, 255, 255, 0);border:none")
        self.linedit_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linedit_res.setReadOnly(True)
        self.linedit_res.setObjectName("linedit_res")
        self.verticalLayout.addWidget(self.linedit_res)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_normal = QtWidgets.QWidget()
        self.tab_normal.setObjectName("tab_normal")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_normal)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_n_percent = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_percent.sizePolicy().hasHeightForWidth())
        self.btn_n_percent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_percent.setFont(font)
        self.btn_n_percent.setAutoFillBackground(False)
        self.btn_n_percent.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_percent.setAutoExclusive(False)
        self.btn_n_percent.setObjectName("btn_n_percent")
        self.btngrp_n_ops = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_n_ops.setObjectName("btngrp_n_ops")
        self.btngrp_n_ops.addButton(self.btn_n_percent)
        self.gridLayout.addWidget(self.btn_n_percent, 0, 0, 1, 1)
        self.btn_n_ce = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_ce.sizePolicy().hasHeightForWidth())
        self.btn_n_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_ce.setFont(font)
        self.btn_n_ce.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_ce.setObjectName("btn_n_ce")
        self.btngrp_n_ops.addButton(self.btn_n_ce)
        self.gridLayout.addWidget(self.btn_n_ce, 0, 1, 1, 1)
        self.btn_n_c = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_c.sizePolicy().hasHeightForWidth())
        self.btn_n_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_c.setFont(font)
        self.btn_n_c.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_c.setObjectName("btn_n_c")
        self.btngrp_n_ops.addButton(self.btn_n_c)
        self.gridLayout.addWidget(self.btn_n_c, 0, 2, 1, 1)
        self.btn_n_backspace = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_backspace.sizePolicy().hasHeightForWidth())
        self.btn_n_backspace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_backspace.setFont(font)
        self.btn_n_backspace.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_backspace.setObjectName("btn_n_backspace")
        self.btngrp_n_ops.addButton(self.btn_n_backspace)
        self.gridLayout.addWidget(self.btn_n_backspace, 0, 3, 1, 1)
        self.btn_n_div = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_div.sizePolicy().hasHeightForWidth())
        self.btn_n_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_div.setFont(font)
        self.btn_n_div.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_n_div.setObjectName("btn_n_div")
        self.btngrp_n_spec = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_n_spec.setObjectName("btngrp_n_spec")
        self.btngrp_n_spec.addButton(self.btn_n_div)
        self.gridLayout.addWidget(self.btn_n_div, 0, 4, 1, 1)
        self.btn_n_sqrt = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_sqrt.sizePolicy().hasHeightForWidth())
        self.btn_n_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_sqrt.setFont(font)
        self.btn_n_sqrt.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_sqrt.setObjectName("btn_n_sqrt")
        self.btngrp_n_ops.addButton(self.btn_n_sqrt)
        self.gridLayout.addWidget(self.btn_n_sqrt, 1, 0, 1, 1)
        self.btn_n_7 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_7.sizePolicy().hasHeightForWidth())
        self.btn_n_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_7.setFont(font)
        self.btn_n_7.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_7.setObjectName("btn_n_7")
        self.btngrp_n_nums = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_n_nums.setObjectName("btngrp_n_nums")
        self.btngrp_n_nums.addButton(self.btn_n_7)
        self.gridLayout.addWidget(self.btn_n_7, 1, 1, 1, 1)
        self.btn_n_8 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_8.sizePolicy().hasHeightForWidth())
        self.btn_n_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_8.setFont(font)
        self.btn_n_8.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_8.setObjectName("btn_n_8")
        self.btngrp_n_nums.addButton(self.btn_n_8)
        self.gridLayout.addWidget(self.btn_n_8, 1, 2, 1, 1)
        self.btn_n_9 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_9.sizePolicy().hasHeightForWidth())
        self.btn_n_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_9.setFont(font)
        self.btn_n_9.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_9.setObjectName("btn_n_9")
        self.btngrp_n_nums.addButton(self.btn_n_9)
        self.gridLayout.addWidget(self.btn_n_9, 1, 3, 1, 1)
        self.btn_n_mul = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_mul.sizePolicy().hasHeightForWidth())
        self.btn_n_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_mul.setFont(font)
        self.btn_n_mul.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_n_mul.setObjectName("btn_n_mul")
        self.btngrp_n_spec.addButton(self.btn_n_mul)
        self.gridLayout.addWidget(self.btn_n_mul, 1, 4, 1, 1)
        self.btn_n_square = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_square.sizePolicy().hasHeightForWidth())
        self.btn_n_square.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_square.setFont(font)
        self.btn_n_square.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_square.setObjectName("btn_n_square")
        self.btngrp_n_ops.addButton(self.btn_n_square)
        self.gridLayout.addWidget(self.btn_n_square, 2, 0, 1, 1)
        self.btn_n_4 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_4.sizePolicy().hasHeightForWidth())
        self.btn_n_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_4.setFont(font)
        self.btn_n_4.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_4.setObjectName("btn_n_4")
        self.btngrp_n_nums.addButton(self.btn_n_4)
        self.gridLayout.addWidget(self.btn_n_4, 2, 1, 1, 1)
        self.btn_n_5 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_5.sizePolicy().hasHeightForWidth())
        self.btn_n_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_5.setFont(font)
        self.btn_n_5.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_5.setObjectName("btn_n_5")
        self.btngrp_n_nums.addButton(self.btn_n_5)
        self.gridLayout.addWidget(self.btn_n_5, 2, 2, 1, 1)
        self.btn_n_6 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_6.sizePolicy().hasHeightForWidth())
        self.btn_n_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_6.setFont(font)
        self.btn_n_6.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_6.setObjectName("btn_n_6")
        self.btngrp_n_nums.addButton(self.btn_n_6)
        self.gridLayout.addWidget(self.btn_n_6, 2, 3, 1, 1)
        self.btn_n_sub = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_sub.sizePolicy().hasHeightForWidth())
        self.btn_n_sub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_sub.setFont(font)
        self.btn_n_sub.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_n_sub.setObjectName("btn_n_sub")
        self.btngrp_n_spec.addButton(self.btn_n_sub)
        self.gridLayout.addWidget(self.btn_n_sub, 2, 4, 1, 1)
        self.btn_n_cube = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_cube.sizePolicy().hasHeightForWidth())
        self.btn_n_cube.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_cube.setFont(font)
        self.btn_n_cube.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_cube.setObjectName("btn_n_cube")
        self.btngrp_n_ops.addButton(self.btn_n_cube)
        self.gridLayout.addWidget(self.btn_n_cube, 3, 0, 1, 1)
        self.btn_n_1 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_1.sizePolicy().hasHeightForWidth())
        self.btn_n_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_1.setFont(font)
        self.btn_n_1.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_1.setObjectName("btn_n_1")
        self.btngrp_n_nums.addButton(self.btn_n_1)
        self.gridLayout.addWidget(self.btn_n_1, 3, 1, 1, 1)
        self.btn_n_2 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_2.sizePolicy().hasHeightForWidth())
        self.btn_n_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_2.setFont(font)
        self.btn_n_2.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_2.setObjectName("btn_n_2")
        self.btngrp_n_nums.addButton(self.btn_n_2)
        self.gridLayout.addWidget(self.btn_n_2, 3, 2, 1, 1)
        self.btn_n_3 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_3.sizePolicy().hasHeightForWidth())
        self.btn_n_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_3.setFont(font)
        self.btn_n_3.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_3.setObjectName("btn_n_3")
        self.btngrp_n_nums.addButton(self.btn_n_3)
        self.gridLayout.addWidget(self.btn_n_3, 3, 3, 1, 1)
        self.btn_n_add = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_add.sizePolicy().hasHeightForWidth())
        self.btn_n_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_add.setFont(font)
        self.btn_n_add.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_n_add.setObjectName("btn_n_add")
        self.btngrp_n_spec.addButton(self.btn_n_add)
        self.gridLayout.addWidget(self.btn_n_add, 3, 4, 1, 1)
        self.btn_n_rec = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_rec.sizePolicy().hasHeightForWidth())
        self.btn_n_rec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_rec.setFont(font)
        self.btn_n_rec.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_rec.setObjectName("btn_n_rec")
        self.btngrp_n_ops.addButton(self.btn_n_rec)
        self.gridLayout.addWidget(self.btn_n_rec, 4, 0, 1, 1)
        self.btn_n_inv = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_inv.sizePolicy().hasHeightForWidth())
        self.btn_n_inv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_inv.setFont(font)
        self.btn_n_inv.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_inv.setObjectName("btn_n_inv")
        self.btngrp_n_ops.addButton(self.btn_n_inv)
        self.gridLayout.addWidget(self.btn_n_inv, 4, 1, 1, 1)
        self.btn_n_0 = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_0.sizePolicy().hasHeightForWidth())
        self.btn_n_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_n_0.setFont(font)
        self.btn_n_0.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_n_0.setObjectName("btn_n_0")
        self.btngrp_n_nums.addButton(self.btn_n_0)
        self.gridLayout.addWidget(self.btn_n_0, 4, 2, 1, 1)
        self.btn_n_dot = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_dot.sizePolicy().hasHeightForWidth())
        self.btn_n_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_dot.setFont(font)
        self.btn_n_dot.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_n_dot.setObjectName("btn_n_dot")
        self.btngrp_n_ops.addButton(self.btn_n_dot)
        self.gridLayout.addWidget(self.btn_n_dot, 4, 3, 1, 1)
        self.btn_n_eql = QtWidgets.QPushButton(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_n_eql.sizePolicy().hasHeightForWidth())
        self.btn_n_eql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_n_eql.setFont(font)
        self.btn_n_eql.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_n_eql.setObjectName("btn_n_eql")
        self.btngrp_n_spec.addButton(self.btn_n_eql)
        self.gridLayout.addWidget(self.btn_n_eql, 4, 4, 1, 1)
        self.tabWidget.addTab(self.tab_normal, "")
        self.tab_science = QtWidgets.QWidget()
        self.tab_science.setObjectName("tab_science")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_science)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_s_deg = QtWidgets.QPushButton(self.tab_science)
        self.btn_s_deg.setStyleSheet("")
        self.btn_s_deg.setFlat(True)
        self.btn_s_deg.setObjectName("btn_s_deg")
        self.horizontalLayout.addWidget(self.btn_s_deg)
        self.btn_s_hyp = QtWidgets.QPushButton(self.tab_science)
        self.btn_s_hyp.setFlat(True)
        self.btn_s_hyp.setObjectName("btn_s_hyp")
        self.horizontalLayout.addWidget(self.btn_s_hyp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_s_sqrt = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_sqrt.sizePolicy().hasHeightForWidth())
        self.btn_s_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_sqrt.setFont(font)
        self.btn_s_sqrt.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_sqrt.setObjectName("btn_s_sqrt")
        self.btngrp_s_ops = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_s_ops.setObjectName("btngrp_s_ops")
        self.btngrp_s_ops.addButton(self.btn_s_sqrt)
        self.gridLayout_2.addWidget(self.btn_s_sqrt, 2, 0, 1, 1)
        self.btn_s_cube = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_cube.sizePolicy().hasHeightForWidth())
        self.btn_s_cube.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_cube.setFont(font)
        self.btn_s_cube.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_cube.setObjectName("btn_s_cube")
        self.btngrp_s_ops.addButton(self.btn_s_cube)
        self.gridLayout_2.addWidget(self.btn_s_cube, 1, 0, 1, 1)
        self.btn_s_tan = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_tan.sizePolicy().hasHeightForWidth())
        self.btn_s_tan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_tan.setFont(font)
        self.btn_s_tan.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_tan.setObjectName("btn_s_tan")
        self.btngrp_s_ops.addButton(self.btn_s_tan)
        self.gridLayout_2.addWidget(self.btn_s_tan, 0, 4, 1, 1)
        self.btn_s_c = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_c.sizePolicy().hasHeightForWidth())
        self.btn_s_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_c.setFont(font)
        self.btn_s_c.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_c.setObjectName("btn_s_c")
        self.btngrp_s_ops.addButton(self.btn_s_c)
        self.gridLayout_2.addWidget(self.btn_s_c, 0, 6, 1, 1)
        self.btn_s_rec = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_rec.sizePolicy().hasHeightForWidth())
        self.btn_s_rec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_rec.setFont(font)
        self.btn_s_rec.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_rec.setObjectName("btn_s_rec")
        self.btngrp_s_ops.addButton(self.btn_s_rec)
        self.gridLayout_2.addWidget(self.btn_s_rec, 3, 0, 1, 1)
        self.btn_s_cos = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_cos.sizePolicy().hasHeightForWidth())
        self.btn_s_cos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_cos.setFont(font)
        self.btn_s_cos.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_cos.setObjectName("btn_s_cos")
        self.btngrp_s_ops.addButton(self.btn_s_cos)
        self.gridLayout_2.addWidget(self.btn_s_cos, 0, 3, 1, 1)
        self.btn_s_square = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_square.sizePolicy().hasHeightForWidth())
        self.btn_s_square.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_square.setFont(font)
        self.btn_s_square.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_square.setObjectName("btn_s_square")
        self.btngrp_s_ops.addButton(self.btn_s_square)
        self.gridLayout_2.addWidget(self.btn_s_square, 0, 0, 1, 1)
        self.btn_s_rand = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_rand.sizePolicy().hasHeightForWidth())
        self.btn_s_rand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_rand.setFont(font)
        self.btn_s_rand.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_rand.setObjectName("btn_s_rand")
        self.btngrp_s_ops.addButton(self.btn_s_rand)
        self.gridLayout_2.addWidget(self.btn_s_rand, 4, 0, 1, 1)
        self.btn_s_sin = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_sin.sizePolicy().hasHeightForWidth())
        self.btn_s_sin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_sin.setFont(font)
        self.btn_s_sin.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_sin.setObjectName("btn_s_sin")
        self.btngrp_s_ops.addButton(self.btn_s_sin)
        self.gridLayout_2.addWidget(self.btn_s_sin, 0, 2, 1, 1)
        self.btn_s_ce = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_ce.sizePolicy().hasHeightForWidth())
        self.btn_s_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_ce.setFont(font)
        self.btn_s_ce.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_ce.setObjectName("btn_s_ce")
        self.btngrp_s_ops.addButton(self.btn_s_ce)
        self.gridLayout_2.addWidget(self.btn_s_ce, 0, 5, 1, 1)
        self.btn_s_pow = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_pow.sizePolicy().hasHeightForWidth())
        self.btn_s_pow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_pow.setFont(font)
        self.btn_s_pow.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_pow.setObjectName("btn_s_pow")
        self.btngrp_s_ops.addButton(self.btn_s_pow)
        self.gridLayout_2.addWidget(self.btn_s_pow, 0, 1, 1, 1)
        self.btn_s_backspace = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_backspace.sizePolicy().hasHeightForWidth())
        self.btn_s_backspace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_backspace.setFont(font)
        self.btn_s_backspace.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_backspace.setObjectName("btn_s_backspace")
        self.btngrp_s_ops.addButton(self.btn_s_backspace)
        self.gridLayout_2.addWidget(self.btn_s_backspace, 0, 7, 1, 1)
        self.btn_s_div = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_div.sizePolicy().hasHeightForWidth())
        self.btn_s_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_div.setFont(font)
        self.btn_s_div.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_s_div.setObjectName("btn_s_div")
        self.btngrp_s_spec = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_s_spec.setObjectName("btngrp_s_spec")
        self.btngrp_s_spec.addButton(self.btn_s_div)
        self.gridLayout_2.addWidget(self.btn_s_div, 0, 8, 1, 1)
        self.btn_s_sqrtx = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_sqrtx.sizePolicy().hasHeightForWidth())
        self.btn_s_sqrtx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_sqrtx.setFont(font)
        self.btn_s_sqrtx.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_sqrtx.setObjectName("btn_s_sqrtx")
        self.btngrp_s_ops.addButton(self.btn_s_sqrtx)
        self.gridLayout_2.addWidget(self.btn_s_sqrtx, 1, 1, 1, 1)
        self.btn_s_10x = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_10x.sizePolicy().hasHeightForWidth())
        self.btn_s_10x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_10x.setFont(font)
        self.btn_s_10x.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_10x.setObjectName("btn_s_10x")
        self.btngrp_s_ops.addButton(self.btn_s_10x)
        self.gridLayout_2.addWidget(self.btn_s_10x, 2, 1, 1, 1)
        self.btn_s_ex = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_ex.sizePolicy().hasHeightForWidth())
        self.btn_s_ex.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_ex.setFont(font)
        self.btn_s_ex.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_ex.setObjectName("btn_s_ex")
        self.btngrp_s_ops.addButton(self.btn_s_ex)
        self.gridLayout_2.addWidget(self.btn_s_ex, 3, 1, 1, 1)
        self.btn_s_pi = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_pi.sizePolicy().hasHeightForWidth())
        self.btn_s_pi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_pi.setFont(font)
        self.btn_s_pi.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_pi.setObjectName("btn_s_pi")
        self.btngrp_s_ops.addButton(self.btn_s_pi)
        self.gridLayout_2.addWidget(self.btn_s_pi, 4, 1, 1, 1)
        self.btn_s_asin = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_asin.sizePolicy().hasHeightForWidth())
        self.btn_s_asin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_asin.setFont(font)
        self.btn_s_asin.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_asin.setObjectName("btn_s_asin")
        self.btngrp_s_ops.addButton(self.btn_s_asin)
        self.gridLayout_2.addWidget(self.btn_s_asin, 1, 2, 1, 1)
        self.btn_s_log = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_log.sizePolicy().hasHeightForWidth())
        self.btn_s_log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_log.setFont(font)
        self.btn_s_log.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_log.setObjectName("btn_s_log")
        self.btngrp_s_ops.addButton(self.btn_s_log)
        self.gridLayout_2.addWidget(self.btn_s_log, 2, 2, 1, 1)
        self.btn_s_ln = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_ln.sizePolicy().hasHeightForWidth())
        self.btn_s_ln.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_ln.setFont(font)
        self.btn_s_ln.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_ln.setObjectName("btn_s_ln")
        self.btngrp_s_ops.addButton(self.btn_s_ln)
        self.gridLayout_2.addWidget(self.btn_s_ln, 3, 2, 1, 1)
        self.btn_s_fact = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_fact.sizePolicy().hasHeightForWidth())
        self.btn_s_fact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_fact.setFont(font)
        self.btn_s_fact.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_fact.setObjectName("btn_s_fact")
        self.btngrp_s_ops.addButton(self.btn_s_fact)
        self.gridLayout_2.addWidget(self.btn_s_fact, 4, 2, 1, 1)
        self.btn_s_acos = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_acos.sizePolicy().hasHeightForWidth())
        self.btn_s_acos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_acos.setFont(font)
        self.btn_s_acos.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_acos.setObjectName("btn_s_acos")
        self.btngrp_s_ops.addButton(self.btn_s_acos)
        self.gridLayout_2.addWidget(self.btn_s_acos, 1, 3, 1, 1)
        self.btn_s_logab = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_logab.sizePolicy().hasHeightForWidth())
        self.btn_s_logab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_logab.setFont(font)
        self.btn_s_logab.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_logab.setObjectName("btn_s_logab")
        self.btngrp_s_ops.addButton(self.btn_s_logab)
        self.gridLayout_2.addWidget(self.btn_s_logab, 2, 3, 1, 1)
        self.btn_s_comb = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_comb.sizePolicy().hasHeightForWidth())
        self.btn_s_comb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.btn_s_comb.setFont(font)
        self.btn_s_comb.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_comb.setObjectName("btn_s_comb")
        self.btngrp_s_ops.addButton(self.btn_s_comb)
        self.gridLayout_2.addWidget(self.btn_s_comb, 3, 3, 1, 1)
        self.btn_s_bra = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_bra.sizePolicy().hasHeightForWidth())
        self.btn_s_bra.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_bra.setFont(font)
        self.btn_s_bra.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_bra.setObjectName("btn_s_bra")
        self.btngrp_s_ops.addButton(self.btn_s_bra)
        self.gridLayout_2.addWidget(self.btn_s_bra, 4, 3, 1, 1)
        self.btn_s_atan = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_atan.sizePolicy().hasHeightForWidth())
        self.btn_s_atan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_atan.setFont(font)
        self.btn_s_atan.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_atan.setObjectName("btn_s_atan")
        self.btngrp_s_ops.addButton(self.btn_s_atan)
        self.gridLayout_2.addWidget(self.btn_s_atan, 1, 4, 1, 1)
        self.btn_s_mod = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_mod.sizePolicy().hasHeightForWidth())
        self.btn_s_mod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_mod.setFont(font)
        self.btn_s_mod.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_mod.setObjectName("btn_s_mod")
        self.btngrp_s_ops.addButton(self.btn_s_mod)
        self.gridLayout_2.addWidget(self.btn_s_mod, 2, 4, 1, 1)
        self.btn_s_perm = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_perm.sizePolicy().hasHeightForWidth())
        self.btn_s_perm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.btn_s_perm.setFont(font)
        self.btn_s_perm.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_perm.setObjectName("btn_s_perm")
        self.btngrp_s_ops.addButton(self.btn_s_perm)
        self.gridLayout_2.addWidget(self.btn_s_perm, 3, 4, 1, 1)
        self.btn_s_ket = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_ket.sizePolicy().hasHeightForWidth())
        self.btn_s_ket.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_ket.setFont(font)
        self.btn_s_ket.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_ket.setObjectName("btn_s_ket")
        self.btngrp_s_ops.addButton(self.btn_s_ket)
        self.gridLayout_2.addWidget(self.btn_s_ket, 4, 4, 1, 1)
        self.btn_s_7 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_7.sizePolicy().hasHeightForWidth())
        self.btn_s_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_7.setFont(font)
        self.btn_s_7.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_7.setObjectName("btn_s_7")
        self.btngrp_s_nums = QtWidgets.QButtonGroup(MainWindow)
        self.btngrp_s_nums.setObjectName("btngrp_s_nums")
        self.btngrp_s_nums.addButton(self.btn_s_7)
        self.gridLayout_2.addWidget(self.btn_s_7, 1, 5, 1, 1)
        self.btn_s_4 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_4.sizePolicy().hasHeightForWidth())
        self.btn_s_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_4.setFont(font)
        self.btn_s_4.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_4.setObjectName("btn_s_4")
        self.btngrp_s_nums.addButton(self.btn_s_4)
        self.gridLayout_2.addWidget(self.btn_s_4, 2, 5, 1, 1)
        self.btn_s_1 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_1.sizePolicy().hasHeightForWidth())
        self.btn_s_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_1.setFont(font)
        self.btn_s_1.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_1.setObjectName("btn_s_1")
        self.btngrp_s_nums.addButton(self.btn_s_1)
        self.gridLayout_2.addWidget(self.btn_s_1, 3, 5, 1, 1)
        self.btn_s_inv = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_inv.sizePolicy().hasHeightForWidth())
        self.btn_s_inv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_inv.setFont(font)
        self.btn_s_inv.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_inv.setObjectName("btn_s_inv")
        self.btngrp_s_ops.addButton(self.btn_s_inv)
        self.gridLayout_2.addWidget(self.btn_s_inv, 4, 5, 1, 1)
        self.btn_s_8 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_8.sizePolicy().hasHeightForWidth())
        self.btn_s_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_8.setFont(font)
        self.btn_s_8.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_8.setObjectName("btn_s_8")
        self.btngrp_s_nums.addButton(self.btn_s_8)
        self.gridLayout_2.addWidget(self.btn_s_8, 1, 6, 1, 1)
        self.btn_s_5 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_5.sizePolicy().hasHeightForWidth())
        self.btn_s_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_5.setFont(font)
        self.btn_s_5.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_5.setObjectName("btn_s_5")
        self.btngrp_s_nums.addButton(self.btn_s_5)
        self.gridLayout_2.addWidget(self.btn_s_5, 2, 6, 1, 1)
        self.btn_s_2 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_2.sizePolicy().hasHeightForWidth())
        self.btn_s_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_2.setFont(font)
        self.btn_s_2.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_2.setObjectName("btn_s_2")
        self.btngrp_s_nums.addButton(self.btn_s_2)
        self.gridLayout_2.addWidget(self.btn_s_2, 3, 6, 1, 1)
        self.btn_s_0 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_0.sizePolicy().hasHeightForWidth())
        self.btn_s_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_0.setFont(font)
        self.btn_s_0.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_0.setObjectName("btn_s_0")
        self.btngrp_s_nums.addButton(self.btn_s_0)
        self.gridLayout_2.addWidget(self.btn_s_0, 4, 6, 1, 1)
        self.btn_s_9 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_9.sizePolicy().hasHeightForWidth())
        self.btn_s_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_9.setFont(font)
        self.btn_s_9.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_9.setObjectName("btn_s_9")
        self.btngrp_s_nums.addButton(self.btn_s_9)
        self.gridLayout_2.addWidget(self.btn_s_9, 1, 7, 1, 1)
        self.btn_s_6 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_6.sizePolicy().hasHeightForWidth())
        self.btn_s_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_6.setFont(font)
        self.btn_s_6.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_6.setObjectName("btn_s_6")
        self.btngrp_s_nums.addButton(self.btn_s_6)
        self.gridLayout_2.addWidget(self.btn_s_6, 2, 7, 1, 1)
        self.btn_s_3 = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_3.sizePolicy().hasHeightForWidth())
        self.btn_s_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btn_s_3.setFont(font)
        self.btn_s_3.setStyleSheet("QPushButton{background: rgba(250, 250, 250,204);border: none;}\n"
"QPushButton:hover{background: rgba(230,230,230, 204);border:none;}\n"
"QPushButton:pressed{background:rgba(210,210,210,204);border:inset;}")
        self.btn_s_3.setObjectName("btn_s_3")
        self.btngrp_s_nums.addButton(self.btn_s_3)
        self.gridLayout_2.addWidget(self.btn_s_3, 3, 7, 1, 1)
        self.btn_s_dot = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_dot.sizePolicy().hasHeightForWidth())
        self.btn_s_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_dot.setFont(font)
        self.btn_s_dot.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(213,213,213,204);border: none;}\n"
"QPushButton:pressed{background:rgba(100, 100, 100, 204);border: none;}")
        self.btn_s_dot.setObjectName("btn_s_dot")
        self.btngrp_s_ops.addButton(self.btn_s_dot)
        self.gridLayout_2.addWidget(self.btn_s_dot, 4, 7, 1, 1)
        self.btn_s_mul = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_mul.sizePolicy().hasHeightForWidth())
        self.btn_s_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_mul.setFont(font)
        self.btn_s_mul.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_s_mul.setObjectName("btn_s_mul")
        self.btngrp_s_spec.addButton(self.btn_s_mul)
        self.gridLayout_2.addWidget(self.btn_s_mul, 1, 8, 1, 1)
        self.btn_s_sub = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_sub.sizePolicy().hasHeightForWidth())
        self.btn_s_sub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_sub.setFont(font)
        self.btn_s_sub.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_s_sub.setObjectName("btn_s_sub")
        self.btngrp_s_spec.addButton(self.btn_s_sub)
        self.gridLayout_2.addWidget(self.btn_s_sub, 2, 8, 1, 1)
        self.btn_s_add = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_add.sizePolicy().hasHeightForWidth())
        self.btn_s_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_add.setFont(font)
        self.btn_s_add.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_s_add.setObjectName("btn_s_add")
        self.btngrp_s_spec.addButton(self.btn_s_add)
        self.gridLayout_2.addWidget(self.btn_s_add, 3, 8, 1, 1)
        self.btn_s_eql = QtWidgets.QPushButton(self.tab_science)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_s_eql.sizePolicy().hasHeightForWidth())
        self.btn_s_eql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s_eql.setFont(font)
        self.btn_s_eql.setStyleSheet("QPushButton{background: rgba(240,240,240,204);border: none;}\n"
"QPushButton:hover{background:rgba(0,119,215,204);border: none;}\n"
"QPushButton:pressed{background:rgba(175, 220, 225, 204);border: none;}")
        self.btn_s_eql.setObjectName("btn_s_eql")
        self.btngrp_s_spec.addButton(self.btn_s_eql)
        self.gridLayout_2.addWidget(self.btn_s_eql, 4, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_science, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 28))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_quit = QtWidgets.QAction(MainWindow)
        self.act_quit.setObjectName("act_quit")
        self.act_undo = QtWidgets.QAction(MainWindow)
        self.act_undo.setObjectName("act_undo")
        self.act_redo = QtWidgets.QAction(MainWindow)
        self.act_redo.setObjectName("act_redo")
        self.act_cut = QtWidgets.QAction(MainWindow)
        self.act_cut.setObjectName("act_cut")
        self.act_copy = QtWidgets.QAction(MainWindow)
        self.act_copy.setObjectName("act_copy")
        self.act_paste = QtWidgets.QAction(MainWindow)
        self.act_paste.setObjectName("act_paste")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setObjectName("act_about")
        self.act_about_qt = QtWidgets.QAction(MainWindow)
        self.act_about_qt.setObjectName("act_about_qt")
        self.action_DEG = QtWidgets.QAction(MainWindow)
        self.action_DEG.setObjectName("action_DEG")
        self.action_RAD = QtWidgets.QAction(MainWindow)
        self.action_RAD.setObjectName("action_RAD")
        self.menu_file.addAction(self.act_quit)
        self.menu_help.addAction(self.act_about)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.act_about_qt)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.linedit_res.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.btn_n_percent.setText(QtWidgets.QApplication.translate("MainWindow", "%", None, -1))
        self.btn_n_ce.setText(QtWidgets.QApplication.translate("MainWindow", "CE", None, -1))
        self.btn_n_c.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.btn_n_backspace.setText(QtWidgets.QApplication.translate("MainWindow", "⌫", None, -1))
        self.btn_n_div.setText(QtWidgets.QApplication.translate("MainWindow", "÷", None, -1))
        self.btn_n_sqrt.setText(QtWidgets.QApplication.translate("MainWindow", "√", None, -1))
        self.btn_n_7.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.btn_n_8.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.btn_n_9.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.btn_n_mul.setText(QtWidgets.QApplication.translate("MainWindow", "×", None, -1))
        self.btn_n_square.setText(QtWidgets.QApplication.translate("MainWindow", "x²", None, -1))
        self.btn_n_4.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.btn_n_5.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.btn_n_6.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.btn_n_sub.setText(QtWidgets.QApplication.translate("MainWindow", "－", None, -1))
        self.btn_n_cube.setText(QtWidgets.QApplication.translate("MainWindow", "x³", None, -1))
        self.btn_n_1.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.btn_n_2.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.btn_n_3.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.btn_n_add.setText(QtWidgets.QApplication.translate("MainWindow", "＋", None, -1))
        self.btn_n_rec.setText(QtWidgets.QApplication.translate("MainWindow", "⅟x", None, -1))
        self.btn_n_inv.setText(QtWidgets.QApplication.translate("MainWindow", "±", None, -1))
        self.btn_n_0.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.btn_n_dot.setText(QtWidgets.QApplication.translate("MainWindow", ".", None, -1))
        self.btn_n_eql.setText(QtWidgets.QApplication.translate("MainWindow", "＝", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_normal), QtWidgets.QApplication.translate("MainWindow", "基本", None, -1))
        self.btn_s_deg.setText(QtWidgets.QApplication.translate("MainWindow", "DEG", None, -1))
        self.btn_s_hyp.setText(QtWidgets.QApplication.translate("MainWindow", "HYP", None, -1))
        self.btn_s_sqrt.setText(QtWidgets.QApplication.translate("MainWindow", "√", None, -1))
        self.btn_s_cube.setText(QtWidgets.QApplication.translate("MainWindow", "x³", None, -1))
        self.btn_s_tan.setText(QtWidgets.QApplication.translate("MainWindow", "tan", None, -1))
        self.btn_s_c.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.btn_s_rec.setText(QtWidgets.QApplication.translate("MainWindow", "⅟x", None, -1))
        self.btn_s_cos.setText(QtWidgets.QApplication.translate("MainWindow", "cos", None, -1))
        self.btn_s_square.setText(QtWidgets.QApplication.translate("MainWindow", "x²", None, -1))
        self.btn_s_rand.setText(QtWidgets.QApplication.translate("MainWindow", "RND", None, -1))
        self.btn_s_sin.setText(QtWidgets.QApplication.translate("MainWindow", "sin", None, -1))
        self.btn_s_ce.setText(QtWidgets.QApplication.translate("MainWindow", "CE", None, -1))
        self.btn_s_pow.setText(QtWidgets.QApplication.translate("MainWindow", "xʸ", None, -1))
        self.btn_s_backspace.setText(QtWidgets.QApplication.translate("MainWindow", "⌫", None, -1))
        self.btn_s_div.setText(QtWidgets.QApplication.translate("MainWindow", "÷", None, -1))
        self.btn_s_sqrtx.setText(QtWidgets.QApplication.translate("MainWindow", "ʸ√x", None, -1))
        self.btn_s_10x.setText(QtWidgets.QApplication.translate("MainWindow", "10ˣ", None, -1))
        self.btn_s_ex.setText(QtWidgets.QApplication.translate("MainWindow", "ℯˣ", None, -1))
        self.btn_s_pi.setText(QtWidgets.QApplication.translate("MainWindow", "π", None, -1))
        self.btn_s_asin.setText(QtWidgets.QApplication.translate("MainWindow", "sin⁻¹", None, -1))
        self.btn_s_log.setText(QtWidgets.QApplication.translate("MainWindow", "log", None, -1))
        self.btn_s_ln.setText(QtWidgets.QApplication.translate("MainWindow", "ln", None, -1))
        self.btn_s_fact.setText(QtWidgets.QApplication.translate("MainWindow", "n!", None, -1))
        self.btn_s_acos.setText(QtWidgets.QApplication.translate("MainWindow", "cos⁻¹", None, -1))
        self.btn_s_logab.setText(QtWidgets.QApplication.translate("MainWindow", "logₐb", None, -1))
        self.btn_s_comb.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.btn_s_bra.setText(QtWidgets.QApplication.translate("MainWindow", "(", None, -1))
        self.btn_s_atan.setText(QtWidgets.QApplication.translate("MainWindow", "tan⁻¹", None, -1))
        self.btn_s_mod.setText(QtWidgets.QApplication.translate("MainWindow", "Mod", None, -1))
        self.btn_s_perm.setText(QtWidgets.QApplication.translate("MainWindow", "P", None, -1))
        self.btn_s_ket.setText(QtWidgets.QApplication.translate("MainWindow", ")", None, -1))
        self.btn_s_7.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.btn_s_4.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.btn_s_1.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.btn_s_inv.setText(QtWidgets.QApplication.translate("MainWindow", "±", None, -1))
        self.btn_s_8.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.btn_s_5.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.btn_s_2.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.btn_s_0.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.btn_s_9.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.btn_s_6.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.btn_s_3.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.btn_s_dot.setText(QtWidgets.QApplication.translate("MainWindow", ".", None, -1))
        self.btn_s_mul.setText(QtWidgets.QApplication.translate("MainWindow", "×", None, -1))
        self.btn_s_sub.setText(QtWidgets.QApplication.translate("MainWindow", "－", None, -1))
        self.btn_s_add.setText(QtWidgets.QApplication.translate("MainWindow", "＋", None, -1))
        self.btn_s_eql.setText(QtWidgets.QApplication.translate("MainWindow", "＝", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_science), QtWidgets.QApplication.translate("MainWindow", "科学", None, -1))
        self.menu_file.setTitle(QtWidgets.QApplication.translate("MainWindow", "文件(&F)", None, -1))
        self.menu_help.setTitle(QtWidgets.QApplication.translate("MainWindow", "帮助(&H)", None, -1))
        self.act_quit.setText(QtWidgets.QApplication.translate("MainWindow", "退出(&Q)", None, -1))
        self.act_undo.setText(QtWidgets.QApplication.translate("MainWindow", "撤销(&U)", None, -1))
        self.act_redo.setText(QtWidgets.QApplication.translate("MainWindow", "重做(&R)", None, -1))
        self.act_cut.setText(QtWidgets.QApplication.translate("MainWindow", "剪切(&X)", None, -1))
        self.act_copy.setText(QtWidgets.QApplication.translate("MainWindow", "复制(&C)", None, -1))
        self.act_paste.setText(QtWidgets.QApplication.translate("MainWindow", "粘贴(&P)", None, -1))
        self.action_3.setText(QtWidgets.QApplication.translate("MainWindow", "简单模式", None, -1))
        self.action_4.setText(QtWidgets.QApplication.translate("MainWindow", "科学模式", None, -1))
        self.act_about.setText(QtWidgets.QApplication.translate("MainWindow", "关于(&A)", None, -1))
        self.act_about_qt.setText(QtWidgets.QApplication.translate("MainWindow", "关于 Qt", None, -1))
        self.action_DEG.setText(QtWidgets.QApplication.translate("MainWindow", "角度制 (DEG)", None, -1))
        self.action_RAD.setText(QtWidgets.QApplication.translate("MainWindow", "弧度制 (RAD)", None, -1))

